### ISSUE TITLE
why do we need host shield there are people who do it with leonardo r3 without host shield how is this possible

### ISSUE THREAD

**Issue by Rentallion** [TrevorSatori/Leonardo#2]
why do we need host shield there are people who do it with leonardo r3 without host shield how is this possible

**Comment by Rentallion** [comment]
how to use this without host shield?
Can you give some support on this?

**Comment by TrevorSatori** [comment]
Absolutely, to understand this better let's differentiate what the 2 items do. The Leonardo acts as input device (this allows us to send serial commands to It through Python and because it operates in a lower ring then video game it works. The host shield is used as a way to use our actual mouse through the Leonardo. This makes it appear as one cohesive device sending inputs as opposed to having the mouse plugged into of sending commands as well as Leonardo. Host shield isn't required though if you're fine with less obfuscation.
